import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:get_storage/get_storage.dart';
import 'package:shajra/features/add_greenhouse/domain/entities/tree_data.dart';
import 'package:shajra/features/add_greenhouse/domain/entities/zone_data.dart';
import '../../domain/entities/greenhouse_entity.dart';
import '../../domain/usecases/create_greenhouse_usecase.dart';

/// A zone drawn within the greenhouse floor on the map canvas.
class GreenhouseMapZone {
  final String id;
  final String name;
  final Rect rect;

  GreenhouseMapZone({
    required this.id,
    required this.name,
    required this.rect,
  });
}

/// A tree placed on the greenhouse map.
class TreePlacement {
  final String id;
  final String? zoneId;
  final Offset position;

  const TreePlacement({
    required this.id,
    this.zoneId,
    required this.position,
  });
}

/// Active tool on the map canvas.
enum MapTool { select, addZone, addTree, addSensor }

/// Controller that manages the three-step greenhouse creation wizard.
class AddGreenhouseController extends GetxController {
  final CreateGreenhouseUseCase _createUseCase;
  final pageController = PageController(initialPage: 0);
  final _storage = GetStorage();

  /// GetStorage key for the wizard draft.
  static const String _draftKey = 'greenhouse_draft';

  AddGreenhouseController(this._createUseCase);

  // ---- Wizard state ----
  final currentStep = 0.obs;
  final totalSteps = 3;

  // ---- Step labels (translated via .tr) ----
  static const stepLabelKeys = [
    'add_gh_step1_label',
    'add_gh_step2_label',
    'add_gh_step3_label',
  ];
  static const facilityTypeKeys = [
    'add_gh_facility_glasshouse',
    'add_gh_facility_polytunnel',
    'add_gh_facility_vertical_farm',
    'add_gh_facility_growth_chamber',
  ];
  static const solarOrientationKeys = [
    'add_gh_orientation_ns',
    'add_gh_orientation_ew',
    'add_gh_orientation_multi',
  ];

  // ---- Form data (step 1) ----
  final nameController = TextEditingController();
  final selectedFacilityType = ''.obs;
  final selectedSolarOrientation = ''.obs;
  final widthController = TextEditingController();
  final heightController = TextEditingController();
  final descriptionController = TextEditingController();

  /// Facility type data values (English, used for storage).
  static const facilityTypes = ['Glasshouse', 'Polytunnel', 'Vertical Farm', 'Growth Chamber'];
  /// Solar orientation data values (English, used for storage).
  static const solarOrientations = ['North-South Alignment', 'East-West Alignment', 'Multi-Span'];

  // ---- Tree grid inputs (step 1) ----
  final lineLengthController = TextEditingController();
  final treesPerLineController = TextEditingController();
  final useLinesCount = true.obs; // true = # of lines, false = spacing between trees
  final linesCountController = TextEditingController();
  final spacingBetweenTreesController = TextEditingController();
  final spacingBetweenLinesController = TextEditingController();
  final autoGenerated = false.obs;
  final estimatedTreeCount = 0.obs;
  final estimatedZoneCount = 0.obs;
  int _greenhouseNumber = 0;

  // ---- Sensor data (step 3) ----
  final selectedSensorType = ''.obs;
  final sensorCountController = TextEditingController();

  // ---- Map state (step 2) ----
  final zones = <GreenhouseMapZone>[].obs;
  final treePlacements = <TreePlacement>[].obs;
  final selectedTool = Rx<MapTool>(MapTool.addZone);
  final transformationController = TransformationController();

  // ---- Submission state ----
  final isSubmitting = false.obs;

  bool get isFirstStep => currentStep.value == 0;
  bool get isLastStep => currentStep.value == totalSteps - 1;

  String get currentStepLabel => stepLabelKeys[currentStep.value].tr;

  /// Zone positions converted to typed ZoneData list.
  List<ZoneData> get zonesData => zones.map((z) {
        final scale = metersToPixels;
        return ZoneData(
          id: z.id,
          name: z.name,
          width: double.parse((z.rect.width / scale).toStringAsFixed(1)),
          height: double.parse((z.rect.height / scale).toStringAsFixed(1)),
          left: double.parse((z.rect.left / scale).toStringAsFixed(1)),
          top: double.parse((z.rect.top / scale).toStringAsFixed(1)),
        );
      }).toList();

  /// Tree positions converted to typed TreeData list.
  List<TreeData> get treesData => treePlacements.map((t) {
        final scale = metersToPixels;
        return TreeData(
          id: t.id,
          zoneId: t.zoneId,
          x: double.parse((t.position.dx / scale).toStringAsFixed(1)),
          y: double.parse((t.position.dy / scale).toStringAsFixed(1)),
        );
      }).toList();

  /// Advance to the next step if the current step is valid.
  void nextStep() {
    _saveDraft(); // persist form data from current step
    if (currentStep.value == 0 && currentStep.value < totalSteps - 1) {
      // When advancing from Step 1 to Step 2, auto-generate layout if not done yet
      if (!autoGenerated.value) {
        generateLayout();
      }
    }
    if (currentStep.value < totalSteps - 1) {
      currentStep.value++;
      pageController.animateToPage(
        currentStep.value,
        duration: const Duration(milliseconds: 300),
        curve: Curves.easeInOut,
      );
    }
  }

  /// Go back one step.
  void previousStep() {
    if (currentStep.value > 0) {
      currentStep.value--;
      pageController.animateToPage(
        currentStep.value,
        duration: const Duration(milliseconds: 300),
        curve: Curves.easeInOut,
      );
    }
  }

  /// Scale factor: 1 meter = 15 pixels on the canvas.
  static const double metersToPixels = 15.0;

  /// Floor dimensions from Step 1, converted to canvas pixels.
  /// Falls back to a default 600×400 if parsing fails.
  double get greenhouseFloorWidthPixels {
    final meters = double.tryParse(widthController.text) ?? 0;
    if (meters <= 0) return 600;
    return (meters * metersToPixels).clamp(300, 3000);
  }

  double get greenhouseFloorHeightPixels {
    final meters = double.tryParse(heightController.text) ?? 0;
    if (meters <= 0) return 400;
    return (meters * metersToPixels).clamp(200, 3000);
  }

  int _computeGreenhouseNumber() {
    // Determine next greenhouse number from existing saved greenhouses + 1
    final saved = _storage.read<List>('saved_greenhouses');
    final count = saved?.length ?? 0;
    return count + 1;
  }

  /// Build a Micro-Tagging tree ID: G{GH:03d}-{Zone}-{Row:02d}-T{Tree:02d}
  String _treeTag(int row, int treeInRow, String zoneName) {
    final gh = _greenhouseNumber.toString().padLeft(3, '0');
    final r = (row + 1).toString().padLeft(2, '0');
    final t = (treeInRow + 1).toString().padLeft(2, '0');
    return 'G$gh-$zoneName-$r-T$t';
  }

  /// Build a Micro-Tagging zone ID: G{GH:03d}-{Zone}
  String _zoneTag(String zoneName) {
    final gh = _greenhouseNumber.toString().padLeft(3, '0');
    return 'G$gh-$zoneName';
  }

  /// Cancel the wizard.
  void cancel() {
    Get.back();
  }

  void _updateEstimate() {
    final lineLen = double.tryParse(lineLengthController.text);
    final treesPerLine = int.tryParse(treesPerLineController.text);
    final spaceBL = double.tryParse(spacingBetweenLinesController.text);

    if (lineLen == null || treesPerLine == null || treesPerLine <= 0 ||
        lineLen <= 0 || spaceBL == null || spaceBL <= 0) {
      estimatedTreeCount.value = 0;
      estimatedZoneCount.value = 0;
      return;
    }

    int numLines;
    if (useLinesCount.value) {
      numLines = int.tryParse(linesCountController.text) ?? 0;
    } else {
      final spacing = double.tryParse(spacingBetweenTreesController.text);
      numLines = spacing != null && spacing > 0 ? (lineLen / spacing).round() : 0;
    }

    if (numLines <= 0) {
      estimatedTreeCount.value = 0;
      estimatedZoneCount.value = 0;
      return;
    }

    final total = treesPerLine * numLines;
    estimatedTreeCount.value = total;
    estimatedZoneCount.value = (total / 50).ceil();
  }

  @override
  void onInit() {
    super.onInit();
    _loadDraft();
    lineLengthController.addListener(_updateEstimate);
    treesPerLineController.addListener(_updateEstimate);
    linesCountController.addListener(_updateEstimate);
    spacingBetweenTreesController.addListener(_updateEstimate);
    spacingBetweenLinesController.addListener(_updateEstimate);
    ever(useLinesCount, (_) => _updateEstimate());
    _updateEstimate(); // compute initial estimate from restored draft values
  }

  /// Persist current wizard state to GetStorage.
  void _saveDraft() {
    _storage.write(_draftKey, {
      'name': nameController.text,
      'facilityType': selectedFacilityType.value,
      'solarOrientation': selectedSolarOrientation.value,
      'width': widthController.text,
      'height': heightController.text,
      'lineLength': lineLengthController.text,
      'treesPerLine': treesPerLineController.text,
      'useLinesCount': useLinesCount.value,
      'linesCount': linesCountController.text,
      'spacingBetweenTrees': spacingBetweenTreesController.text,
      'spacingBetweenLines': spacingBetweenLinesController.text,
      'sensorType': selectedSensorType.value,
      'sensorCount': sensorCountController.text,
      'zones': zones.map((z) => {
            'id': z.id,
            'name': z.name,
            'left': z.rect.left,
            'top': z.rect.top,
            'width': z.rect.width,
            'height': z.rect.height,
          }).toList(),
      'trees': treePlacements.map((t) => {
            'id': t.id,
            'zoneId': t.zoneId,
            'dx': t.position.dx,
            'dy': t.position.dy,
          }).toList(),
    });
  }

  /// Restore wizard state from GetStorage.
  void _loadDraft() {
    final data = _storage.read<Map>(_draftKey);
    if (data == null) return;
    nameController.text = data['name'] ?? '';
    selectedFacilityType.value = data['facilityType'] ?? '';
    selectedSolarOrientation.value = data['solarOrientation'] ?? '';
    widthController.text = data['width'] ?? '';
    heightController.text = data['height'] ?? '';
    lineLengthController.text = data['lineLength'] ?? '';
    treesPerLineController.text = data['treesPerLine'] ?? '';
    useLinesCount.value = data['useLinesCount'] as bool? ?? true;
    linesCountController.text = data['linesCount'] ?? '';
    spacingBetweenTreesController.text = data['spacingBetweenTrees'] ?? '';
    spacingBetweenLinesController.text = data['spacingBetweenLines'] ?? '';
    selectedSensorType.value = data['sensorType'] ?? '';
    sensorCountController.text = data['sensorCount'] ?? '';

    final zoneList = data['zones'] as List?;
    if (zoneList != null) {
      zones.value = zoneList.map((z) => GreenhouseMapZone(
            id: z['id'] as String,
            name: z['name'] as String,
            rect: Rect.fromLTWH(
              (z['left'] as num).toDouble(),
              (z['top'] as num).toDouble(),
              (z['width'] as num).toDouble(),
              (z['height'] as num).toDouble(),
            ),
          )).toList();
    }

    final treeList = data['trees'] as List?;
    if (treeList != null) {
      treePlacements.value = treeList.map((t) => TreePlacement(
            id: t['id'] as String,
            zoneId: t['zoneId'] as String?,
            position: Offset(
              (t['dx'] as num).toDouble(),
              (t['dy'] as num).toDouble(),
            ),
          )).toList();
    }
  }

  /// Add a new zone to the map (rect in canvas pixels).
  void addZone(Rect rect) {
    if (_greenhouseNumber <= 0) {
      _greenhouseNumber = _computeGreenhouseNumber();
    }
    final zoneName = 'Zone${String.fromCharCode(65 + zones.length)}';
    zones.add(GreenhouseMapZone(
      id: _zoneTag(zoneName),
      name: zoneName,
      rect: rect,
    ));
    _saveDraft();
  }

  /// Rename a zone by its ID.
  void renameZone(String id, String newName) {
    final index = zones.indexWhere((z) => z.id == id);
    if (index >= 0) {
      final z = zones[index];
      zones[index] = GreenhouseMapZone(
        id: z.id,
        name: newName,
        rect: z.rect,
      );
      _saveDraft();
    }
  }

  /// Shift a zone by [dx, dy] pixels to support drag-to-move.
  void moveZone(String id, double dx, double dy) {
    final index = zones.indexWhere((z) => z.id == id);
    if (index >= 0) {
      final z = zones[index];
      zones[index] = GreenhouseMapZone(
        id: z.id,
        name: z.name,
        rect: z.rect.shift(Offset(dx, dy)),
      );
      _saveDraft();
    }
  }

  /// Add a tree at the given position (relative to the virtual floor).
  void addTree(Offset position, {String? zoneId}) {
    if (_greenhouseNumber <= 0) {
      _greenhouseNumber = _computeGreenhouseNumber();
    }
    // For manual placement, use a sequential tag
    final gh = _greenhouseNumber.toString().padLeft(3, '0');
    final idx = (treePlacements.length + 1).toString().padLeft(2, '0');
    final id = 'G$gh-M$idx';
    treePlacements.add(TreePlacement(
      id: id,
      zoneId: zoneId,
      position: position,
    ));
    _saveDraft();
  }

  /// Zoom in by 25%.
  void zoomIn() {
    final currentScale = transformationController.value.getMaxScaleOnAxis();
    final newScale = (currentScale * 1.25).clamp(0.5, 4.0);
    final matrix = Matrix4.diagonal3Values(newScale, newScale, 1);
    transformationController.value = matrix;
  }

  /// Zoom out by 20%.
  void zoomOut() {
    final currentScale = transformationController.value.getMaxScaleOnAxis();
    final newScale = (currentScale / 1.25).clamp(0.5, 4.0);
    final matrix = Matrix4.diagonal3Values(newScale, newScale, 1);
    transformationController.value = matrix;
  }

  /// Submit the greenhouse and navigate back.
  Future<void> submit() async {
    isSubmitting.value = true;
    try {
      final greenhouse = GreenhouseEntity(
        name: nameController.text.trim(),
        description: '',
        facilityType: selectedFacilityType.value,
        solarOrientation: selectedSolarOrientation.value,
        width: double.tryParse(widthController.text) ?? 0,
        height: double.tryParse(heightController.text) ?? 0,
        sensorType: selectedSensorType.value.isNotEmpty
            ? selectedSensorType.value
            : null,
        sensorCount: int.tryParse(sensorCountController.text),
        zonesData: zonesData,
        treesData: treesData,
      );
      await _createUseCase(greenhouse);
      _storage.remove(_draftKey);
      Get.back(result: true);
    } finally {
      isSubmitting.value = false;
    }
  }

  /// Auto-generate the tree grid and zones based on the tree grid inputs.
  void generateLayout() {
    _greenhouseNumber = _computeGreenhouseNumber();

    final lineLen = double.tryParse(lineLengthController.text);
    final treesPerLine = int.tryParse(treesPerLineController.text);
    final spaceBetweenLines = double.tryParse(spacingBetweenLinesController.text);

    if (lineLen == null || treesPerLine == null || treesPerLine <= 0 ||
        lineLen <= 0 || spaceBetweenLines == null || spaceBetweenLines <= 0) {
      return; // not enough data to generate
    }

    int numLines;
    if (useLinesCount.value) {
      numLines = int.tryParse(linesCountController.text) ?? 0;
      if (numLines <= 0) return;
    } else {
      final spacing = double.tryParse(spacingBetweenTreesController.text);
      if (spacing == null || spacing <= 0) return;
      numLines = (lineLen / spacing).round();
      if (numLines <= 0) return;
    }

    final scale = metersToPixels;
    final greenW = greenhouseFloorWidthPixels;
    final greenH = greenhouseFloorHeightPixels;

    // Calculate spacing along the row
    final spacingAlongRow = treesPerLine > 1 ? lineLen / (treesPerLine - 1) : lineLen;

    // Total width of the tree grid in meters
    final gridWidthM = lineLen;
    final gridHeightM = (numLines - 1) * spaceBetweenLines;

    // Convert to pixels
    final gridWidthPx = gridWidthM * scale;
    final gridHeightPx = gridHeightM * scale;

    // Center the grid within the greenhouse floor
    final offsetX = (greenW - gridWidthPx) / 2;
    final offsetY = (greenH - gridHeightPx) / 2;

    // --- Generate zones first (so tree IDs can reference them) ---
    final totalTrees = treesPerLine * numLines;
    if (totalTrees <= 0) return;

    const maxTreesPerZone = 50;
    final numZones = (totalTrees / maxTreesPerZone).ceil();
    final treesPerZone = (totalTrees / numZones).ceil();

    // Determine zone names and row ranges for each zone
    final zoneRowRanges = <(int startRow, int endRow, String name)>[];
    for (int z = 0; z < numZones; z++) {
      final startTreeIdx = z * treesPerZone;
      final endTreeIdx = (startTreeIdx + treesPerZone).clamp(0, totalTrees);
      if (startTreeIdx >= totalTrees) break;

      // Map tree index range to row range
      final startRow = startTreeIdx ~/ treesPerLine;
      final endRow = ((endTreeIdx - 1) ~/ treesPerLine).clamp(0, numLines - 1);
      final zoneName = 'Zone${String.fromCharCode(65 + z)}';
      zoneRowRanges.add((startRow, endRow, zoneName));
    }

    // --- Generate trees with Micro-Tagging IDs ---
    final newTrees = <TreePlacement>[];
    for (int line = 0; line < numLines; line++) {
      for (int t = 0; t < treesPerLine; t++) {
        final px = offsetX + t * spacingAlongRow * scale;
        final py = offsetY + line * spaceBetweenLines * scale;

        // Determine which zone this tree belongs to
        String? zoneId;
        String zoneName = 'ZoneA';
        for (final (startRow, endRow, name) in zoneRowRanges) {
          if (line >= startRow && line <= endRow) {
            zoneName = name;
            zoneId = _zoneTag(zoneName);
            break;
          }
        }

        final treeId = _treeTag(line, t, zoneName);
        newTrees.add(TreePlacement(
          id: treeId,
          zoneId: zoneId,
          position: Offset(px, py),
        ));
      }
    }

    // --- Generate zones ---
    final newZones = <GreenhouseMapZone>[];
    for (int z = 0; z < zoneRowRanges.length; z++) {
      final (startRow, endRow, zoneName) = zoneRowRanges[z];

      // Calculate bounding rect of trees in this zone's rows
      double minX = double.infinity, minY = double.infinity;
      double maxX = double.negativeInfinity, maxY = double.negativeInfinity;
      for (final tree in newTrees) {
        if (tree.zoneId == _zoneTag(zoneName)) {
          if (tree.position.dx < minX) minX = tree.position.dx;
          if (tree.position.dy < minY) minY = tree.position.dy;
          if (tree.position.dx > maxX) maxX = tree.position.dx;
          if (tree.position.dy > maxY) maxY = tree.position.dy;
        }
      }

      final padding = 10.0;
      final zoneRect = Rect.fromLTRB(
        (minX - padding).clamp(0, greenW),
        (minY - padding).clamp(0, greenH),
        (maxX + padding).clamp(0, greenW),
        (maxY + padding).clamp(0, greenH),
      );

      newZones.add(GreenhouseMapZone(
        id: _zoneTag(zoneName),
        name: zoneName,
        rect: zoneRect,
      ));
    }

    zones.value = newZones;
    treePlacements.value = newTrees;
    autoGenerated.value = true;
    _saveDraft();
  }

  /// Remove a zone by ID (called from the view in remove mode).
  void removeZone(String id) {
    zones.removeWhere((z) => z.id == id);
    _saveDraft();
  }

  /// Remove a tree by ID.
  void removeTree(String id) {
    treePlacements.removeWhere((t) => t.id == id);
    _saveDraft();
  }

  @override
  void onClose() {
    pageController.dispose();
    transformationController.dispose();
    nameController.dispose();
    widthController.dispose();
    heightController.dispose();
    lineLengthController.dispose();
    treesPerLineController.dispose();
    linesCountController.dispose();
    spacingBetweenTreesController.dispose();
    spacingBetweenLinesController.dispose();
    sensorCountController.dispose();
    super.onClose();
  }
}
